### ISSUE TITLE
Toolbar not showing

### ISSUE THREAD

**Issue by eamaral92** [ipeychev/alloyeditor-react-component#8]
I install the plugin on a static HTML page, the editor is working PERFECTLY, it's save my ass!
But for some reason, the toolbar is not showing, since yesterday i`m debuing the code but nothing...
Can you guide me in the configuration?

**Comment by ipeychev** [comment]
Hello,

Could you provide your current configuration?

Thanks,

**Comment by eamaral92** [comment]
At this moment, is just the default setting: 
var editor = AlloyEditor.editable('page-top');
The alloy is in the root of the document.

**Comment by ipeychev** [comment]
There might be multiple reasons, like:
1. Is there an element with ID `page-top`?
2. Are there any errors in the console? Maybe for some reason the editor was not loaded properly?

Did you try to load the editor not as React component, but to place the script directly on the page?

Thanks,

**Comment by eamaral92** [comment]
1. The element exists
2. No errors referring to the Alloy
3. Yes i try and nothing happens...

**Comment by eamaral92** [comment]
I post the Issue in the wrong repository... Sorry about that. I can change this issue to the right repo of the Alloy core if you want...

**Comment by ipeychev** [comment]
You can leave the issue here, this is not a problem.

Are you sure this code is executed:

``` javascript
var editor = AlloyEditor.editable('page-top');
```

Why don't you try to do the following:

``` javascript
window.editor = AlloyEditor.editable('page-top');
```

and then from the browser console to try to access the editor, like this:

``` javascript
var data = window.editor.get('nativeEditor').getData();
console.log('DATA', data);
```

Then, we will see what is the content of this `page-top` element and we will be sure you are actually creating an instance of AlloyEditor.

**Comment by abejfehr** [comment]
@eamaral92 are there 404's in the browser?

I'm having this same issue right now, and I'm realizing that it's because of the `window.ALLOYEDITOR_BASEPATH` and `window.CKEDITOR_BASEPATH` locations. It seems like `../node_modules/` is meant to access the node modules folder in the parent directory, but this isn't possible because the `node_modules` folder isn't accessible from the front end -- I expected every needed module (and their dependencies) to have been packaged in the bundle.

**Comment by ipeychev** [comment]
@abejfehr,

It would be a performance penalty to bundle everything in the bundle. There are about 60+ language files and only one is needed. That's why it is being retrieved dynamically. CKEditor does the same with its config files.

Hope that helps.

Thanks,

**Comment by bradennapier** [comment]
Hmm so what are the instructions to make this work?  I also do not see the toolbar, I have installed alloyeditor - do I also need to separately build the ckeditor to make this work?

**Comment by ipeychev** [comment]
@bradennapier No, it is not needed. Please check for errors in the console, check if the editor is being instantiated, the editable element exists, check again if you are following the advices in the current repository, etc.
If this does not help and you are sure you do everything properly, please provide a simple reproducible code and I will take a look.

Thanks,

**Comment by skywickenden** [comment]
I had this problem.

There were no errors in the console. The editor was working. The text is styled and editable. However when I select some text the toolbar does not pop up. Also the 'plus' icon to the left is missing.

The problem was that I was not incuding the theme stylesheet.

```
import 'alloyeditor/dist/alloy-editor/assets/alloy-editor-ocean-min.css';
```

( @ipeychev Thanks for making this and being so active in the support).

**Comment by ipeychev** [comment]
You are welcome! Happy you resolved the issue!
